namespace HeCopUI_Framework.Win32.Enums
{
    public enum ACCENT_STATE
    {
        ACCENT_DISABLED,
        ACCENT_ENABLE_GRADIENT,
        ACCENT_ENABLE_TRANSPARENTGRADIENT,
        ACCENT_ENABLE_BLURBEHIND,
        ACCENT_ENABLE_ACRYLICBLURBEHIND,
        ACCENT_INVALID_STATE
    }
}
